import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>ぐるめいと</h1>
        <ul className={styles.shopList}>
          {results.shop && results.shop.map((data, i) => {
            return (
              <li key={i} className={styles.shop}>
                <div className={styles.leftSide}>
                  <a href={data.urls.pc}>
                    <Image
                      src={data.photo.pc.m}
                      alt={data.name}
                      width={168}
                      height={168}
                    />
                  </a>
                </div>
                <div className={styles.rightSide}>
                  <div className={styles.catch}>{data.catch}</div>
                  <h3 className={styles.name}>
                    <a href={data.urls.pc}>{data.name}</a>
                  </h3>
                  <div className={styles.address}>
                    <span className={styles.bold}>住所：</span>
                    {data.address}
                  </div>
                  <div className={styles.open}>
                    <span className={styles.bold}>営業時間：</span>
                    {data.open}
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const apiKey = process.env.API_KEY;
    const baseUrl = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/";
    const serviceAria = "SA91"; 
    const format = "json"; // XMLフォーマットなのでJSONに

    // APIからデータをFetchします。
    const res = await fetch(
      `${baseUrl}?key=${apiKey}&service_area=${serviceAria}&format=${format}`
    );
    
    if (!res.ok) {
      throw new Error("Failed to fetch data from the API");
    }

    const json = await res.json();
    const { results } = json;

    return { props: { results } };
  } catch (error) {
    console.error("Error fetching data:", error.message);
    return { props: { results: null } }; // またはエラー時のデフォルトの値を返すなど
  }
}
